name: 'simple workflow pm2'
on: [push]
jobs:
  check-pm2-version:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v1
      - run: npm install -g pm2
      - run: pm2 -v